package br.gov.caixa.arqrefservices.dominio.consignet.common;

public enum TipoConsignet {

	USUARIO_CONVENIO("USUARIO_CONVENIO"),
	SENHA_CONVENIO("SENHA_CONVENIO"),
	MATRICULA("MATRICULA"),
	CNPJ_CONVENENTE("CNPJ_CONVENENTE"),
	CPF("CPF"),
	ORIGEM("ORIGEM"),
	SENHA_SERVIDOR("SENHA_SERVIDOR"),
	CONVENIO("CONVENIO"),
	VL_PARCELA("VL_PARCELA"),
	QTDE_PARCELA("QTDE_PARCELA"),
	JUROS_MENSAL("JUROS_MENSAL"),
	VL_LIQUIDO_LIBERADO("VL_LIQUIDO_LIBERADO"),
	DT_LIBERACAO_CREDITO("DT_LIBERACAO_CREDITO"),
	FOLHA_1_DESCONTO("FOLHA_1_DESCONTO"),
	CONTRATOS("CONTRATOS"),
	CONTRATO("CONTRATO"),
	CONTRATO_CONVENIO("CONTRATO_CONVENIO"),
	ACEITO("ACEITO"),
	MOTIVO_RECUSA("MOTIVO_RECUSA"),
	NR_CONTRATO_CONVENIO("NR_CONTRATO_CONVENIO"),
	VL_LIBERADO_CONFIRMACAO("VL_LIBERADO_CONFIRMACAO"),
	VL_PARCELA_CONFIRMACAO("VL_PARCELA_CONFIRMACAO"),
	JUROS_CONFIRMACAO("JUROS_CONFIRMACAO"),
	CET_CONFIRMACAO("CET_CONFIRMACAO"),
	VL_COBRADO_QUITACAO("VL_COBRADO_QUITACAO"),
	JUSTIFICATIVA("JUSTIFICATIVA"),
	USUARIO("USUARIO"),
	SENHA("SENHA"),
	FOLHA_CONSULTA("FOLHA_CONSULTA"),
	INSTITUICAO("INSTITUICAO"),
	ANO_MES_FOLHA_PAGAMENTO("ANO_MES_FOLHA_PAGAMENTO"),
	ID_FOLHA_PAGAMENTO("ID_FOLHA_PAGAMENTO"),
	TAC("TAC"),
	IOF("IOF"),
	DIAS_CARENCIA("DIAS_CARENCIA"),
	VLR_COBRADO_CARENCIA("VLR_COBRADO_CARENCIA"),
	CUSTO_EFETIVO_TOTAL("CUSTO_EFETIVO_TOTAL"),
	VL_TOTAL_FINANCIADO("VL_TOTAL_FINANCIADO");
		
	private String name;
	
	private TipoConsignet(String nome) {
		this.name = nome;
	}
	
	public String getNome() {
		return name;
	}
	
}
